# Generated by Django 5.1.2 on 2024-10-31 06:41

import PKMApi.yandex_s3_storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0.0', verbose_name='Версия приложения')),
                ('upd', models.DateField(verbose_name='Обновление от')),
                ('address', models.CharField(verbose_name='Адрес')),
                ('info', models.CharField(default='0', verbose_name='Информация')),
                ('instruction', models.CharField(default='0', verbose_name='Инструкция по эксплуатации')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indent', models.IntegerField(default=0, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Название участка')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'db_table': 'Area',
            },
        ),
        migrations.CreateModel(
            name='Batcharchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(default=0, max_length=100, unique=True)),
                ('technology_number', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Batcharchive',
            },
        ),
        migrations.CreateModel(
            name='Batchstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Batchstatus',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код компании')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплата')),
                ('paid_machines_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество оплаченных машин')),
                ('date_of_start', models.DateField(blank=True, null=True, verbose_name='Дата начала подписки')),
                ('date_of_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('is_testdrive', models.BooleanField(default=True, verbose_name='Тестовый период')),
                ('number_of_support_staff', models.IntegerField(default=0, verbose_name='Количество персонала')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indent', models.PositiveIntegerField(default=0, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Название цеха')),
                ('main_user', models.CharField(verbose_name='Начальник цеха')),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цеха',
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Orderstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Orderstatus',
            },
        ),
        migrations.CreateModel(
            name='Reporttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Reporttype',
            },
        ),
        migrations.CreateModel(
            name='ShiftDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название дня недели')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
                'db_table': 'ShiftDay',
            },
        ),
        migrations.CreateModel(
            name='Stagestatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Stagestatus',
            },
        ),
        migrations.CreateModel(
            name='Workstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Workstatus',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('technology', models.TextField(blank=True, null=True)),
                ('isready', models.BooleanField(default=False)),
                ('rs_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bath_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batcharchive')),
                ('batch_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batchstatus')),
            ],
            options={
                'db_table': 'Batch',
            },
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код бригады')),
                ('name', models.CharField(max_length=255, verbose_name='Название бригады')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.area', verbose_name='Участок')),
            ],
        ),
        migrations.CreateModel(
            name='Chiefbatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batchstatus')),
                ('bath', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batch')),
            ],
            options={
                'db_table': 'Chiefbatch',
            },
        ),
        migrations.AddField(
            model_name='batcharchive',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company'),
        ),
        migrations.AddField(
            model_name='area',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.department', verbose_name='Название цеха'),
        ),
        migrations.CreateModel(
            name='MachineControlMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Способ управления оборудованием',
                'verbose_name_plural': 'Способы управления оборудованием',
                'db_table': 'MachineControlMethod',
            },
        ),
        migrations.CreateModel(
            name='MachineStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Вид оборудования',
                'verbose_name_plural': 'Виды оборудования',
                'db_table': 'MachineStyle',
            },
        ),
        migrations.CreateModel(
            name='MachineGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('style', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Core.machinestyle', verbose_name='Вид оборудования')),
            ],
            options={
                'verbose_name': 'Группа оборудования',
                'verbose_name_plural': 'Группы оборудования',
                'db_table': 'MachineGroup',
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.machinegroup', verbose_name='Группа оборудования')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'db_table': 'MachineType',
            },
        ),
        migrations.CreateModel(
            name='MachineName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.PositiveIntegerField(verbose_name='Инвентарный номер')),
                ('machine_code', models.CharField(max_length=100, verbose_name='Модель')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('surname', models.CharField(max_length=255, verbose_name='Дополнительное название')),
                ('img', models.FileField(blank=True, null=True, storage=PKMApi.yandex_s3_storage.ClientImgStorage(), upload_to='', verbose_name='Фотография')),
                ('ratio', models.PositiveIntegerField(default=0, verbose_name='Коэффициент многостаночности')),
                ('tarife', models.PositiveIntegerField(default=0, verbose_name='Сдельный тариф')),
                ('work_time', models.CharField(null=True, verbose_name='Время работы')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.area', verbose_name='Участок')),
                ('brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.brigade', verbose_name='Бригада')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Компания')),
                ('machine_control_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.machinecontrolmethod', verbose_name='Способ управления оборудованием')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.machinetype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Карточка оборудования',
                'verbose_name_plural': 'Карточки оборудования',
                'db_table': 'MachineName',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('date_receipt', models.DateField()),
                ('required_completion_date', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField()),
                ('calculated_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('customer', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company')),
                ('order_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.orderstatus')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.order'),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indent', models.PositiveIntegerField(default=0, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=255, verbose_name='Название площадки')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес площадки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'db_table': 'Platform',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.platform', verbose_name='Название площадки'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роль',
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='ShiftMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код режима сменности')),
                ('work_hours_per_day', models.PositiveIntegerField(verbose_name='Рабочих часов в день')),
                ('shifts_per_day', models.PositiveIntegerField(verbose_name='Смен в сутках')),
                ('hours_in_shifts', models.PositiveIntegerField(verbose_name='Часов в смене')),
                ('work_days_inline', models.PositiveIntegerField(verbose_name='Рабочих дней в подряд')),
                ('weekends_inline', models.PositiveIntegerField(verbose_name='Выходных дней в подряд')),
                ('shift_working_day_mode', models.CharField(verbose_name='Режимы рабочего дня')),
                ('work_days_per_week', models.PositiveIntegerField(verbose_name='Рабочих дней в неделе')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Режим сменности',
                'verbose_name_plural': 'Режимы сменности',
                'db_table': 'ShiftMode',
            },
        ),
        migrations.CreateModel(
            name='ShiftWorkingDayMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код рабочего дня')),
                ('name', models.CharField(max_length=255, verbose_name='Названние режима рабочего дня')),
                ('start_time', models.TimeField(verbose_name='Время начала смены')),
                ('end_time', models.TimeField(verbose_name='Время конца смены')),
                ('start_pause_1', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 1')),
                ('end_pause_1', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 1')),
                ('start_pause_2', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 2')),
                ('end_pause_2', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 2')),
                ('start_pause_3', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 3')),
                ('end_pause_3', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 3')),
                ('start_pause_4', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 4')),
                ('end_pause_4', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 4')),
                ('start_pause_5', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 5')),
                ('end_pause_5', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 5')),
                ('start_pause_6', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 6')),
                ('end_pause_6', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 6')),
                ('start_pause_7', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 7')),
                ('end_pause_7', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 7')),
                ('start_pause_8', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 8')),
                ('end_pause_8', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 8')),
                ('start_pause_9', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 9')),
                ('end_pause_9', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 9')),
                ('start_pause_10', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 10')),
                ('end_pause_10', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 10')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Режим рабочего дня',
                'verbose_name_plural': 'Режимы рабочего дня',
                'db_table': 'ShiftWorkingDayMode',
            },
        ),
        migrations.CreateModel(
            name='ShiftCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.shiftday', verbose_name='День недели')),
                ('shift_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.shiftmode', verbose_name='Режим сменности')),
                ('shift_working_day_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.shiftworkingdaymode', verbose_name='Режим рабочего дня')),
            ],
            options={
                'verbose_name': 'Календарь',
                'verbose_name_plural': 'Календари',
                'db_table': 'ShiftCalendar',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isdistributed', models.BooleanField(default=False)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.area')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batch')),
                ('batch_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batcharchive')),
            ],
            options={
                'db_table': 'Stage',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('time_pz', models.DurationField(blank=True, null=True)),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.stage')),
            ],
            options={
                'db_table': 'Operation',
            },
        ),
        migrations.CreateModel(
            name='Chiefdistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batch')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.department')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.operation')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.stage')),
            ],
            options={
                'db_table': 'Chiefdistribution',
            },
        ),
        migrations.CreateModel(
            name='Stagearchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batcharchive')),
            ],
            options={
                'db_table': 'Stagearchive',
            },
        ),
        migrations.CreateModel(
            name='Operationarchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('time_pz', models.DurationField(blank=True, null=True)),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('stage_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.stagearchive')),
            ],
            options={
                'db_table': 'Operationarchive',
            },
        ),
        migrations.CreateModel(
            name='Stagedistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.chiefbatch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.department')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.stage')),
                ('stage_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.stagestatus')),
            ],
            options={
                'db_table': 'Stagedistribution',
            },
        ),
        migrations.CreateModel(
            name='Chiefoperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_distributed', models.BooleanField(default=False)),
                ('chief_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.chiefbatch')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.operation')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.stage')),
                ('distribution_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.stagedistribution')),
            ],
            options={
                'db_table': 'Chiefoperation',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название подразделения')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'db_table': 'Subdivision',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.operation')),
            ],
            options={
                'db_table': 'Transfer',
            },
        ),
        migrations.CreateModel(
            name='Transferarchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('operation_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.operationarchive')),
            ],
            options={
                'db_table': 'Transferarchive',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('profile_picture', models.FileField(blank=True, null=True, storage=PKMApi.yandex_s3_storage.ClientImgStorage(), upload_to='', verbose_name='Фотография')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('is_activated', models.BooleanField(blank=True, default=False, null=True, verbose_name='Подтверждённый')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Компания')),
                ('role_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_1_users', to='Core.role', verbose_name='Роль 1')),
                ('role_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_2_users', to='Core.role', verbose_name='Роль 2')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.subdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Uploadedreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=0, max_length=100)),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.reporttype')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.user')),
            ],
            options={
                'db_table': 'Uploadedreport',
            },
        ),
        migrations.CreateModel(
            name='RoleOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.area', verbose_name='Площадка')),
                ('role_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.role', verbose_name='Название роли')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Роль оператора',
                'verbose_name_plural': 'Роль операторов',
                'db_table': 'RoleOperator',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.user')),
            ],
            options={
                'db_table': 'Allocation',
            },
        ),
    ]
