# Generated by Django 5.1.2 on 2024-10-17 10:40

import PKMApi.yandex_s3_storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batcharchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(default=0, max_length=100, unique=True)),
                ('technology_number', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Batcharchive',
            },
        ),
        migrations.CreateModel(
            name='Batchstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Batchstatus',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('code', models.CharField(max_length=100, verbose_name='Код компании')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплата')),
                ('paid_machines_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество оплаченных машин')),
                ('date_of_start', models.DateField(blank=True, null=True, verbose_name='Дата начала подписки')),
                ('date_of_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания подписки')),
                ('is_testdrive', models.BooleanField(default=True, verbose_name='Тестовый период')),
                ('number_of_support_staff', models.IntegerField(default=0, verbose_name='Количество персонала')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цеха')),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цеха',
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Firstmachinetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Firstmachinetype',
            },
        ),
        migrations.CreateModel(
            name='Orderstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Orderstatus',
            },
        ),
        migrations.CreateModel(
            name='Reporttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Reporttype',
            },
        ),
        migrations.CreateModel(
            name='Secondmachinetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Secondmachinetype',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Shift',
            },
        ),
        migrations.CreateModel(
            name='Shiftschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_change', models.TimeField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('time_first', models.TimeField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Shiftschedule',
            },
        ),
        migrations.CreateModel(
            name='Stagestatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Stagestatus',
            },
        ),
        migrations.CreateModel(
            name='Workstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Workstatus',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('technology', models.TextField(blank=True, null=True)),
                ('isready', models.BooleanField(default=False)),
                ('rs_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bath_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batcharchive')),
                ('batch_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batchstatus')),
            ],
            options={
                'db_table': 'Batch',
            },
        ),
        migrations.CreateModel(
            name='Chiefbatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batchstatus')),
                ('bath', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batch')),
            ],
            options={
                'db_table': 'Chiefbatch',
            },
        ),
        migrations.AddField(
            model_name='batcharchive',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название участка')),
                ('indent', models.IntegerField(default=0, verbose_name='Идентификатор')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.department', verbose_name='Название цеха')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'db_table': 'Area',
            },
        ),
        migrations.CreateModel(
            name='Detailmachinetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.firstmachinetype')),
            ],
            options={
                'db_table': 'Detailmachinetype',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invent_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_activated', models.BooleanField(default=False)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.area')),
                ('detail_machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.detailmachinetype')),
                ('first_machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.firstmachinetype')),
                ('second_machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.secondmachinetype')),
                ('shift_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.shiftschedule')),
            ],
            options={
                'db_table': 'Machine',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('date_receipt', models.DateField()),
                ('required_completion_date', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField()),
                ('calculated_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('customer', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company')),
                ('order_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.orderstatus')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.order'),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название площадки')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес площадки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'db_table': 'Platform',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.platform', verbose_name='Название площадки'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роль',
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isdistributed', models.BooleanField(default=False)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.area')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batch')),
                ('batch_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batcharchive')),
            ],
            options={
                'db_table': 'Stage',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('time_pz', models.DurationField(blank=True, null=True)),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.stage')),
            ],
            options={
                'db_table': 'Operation',
            },
        ),
        migrations.CreateModel(
            name='Chiefdistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batch')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.department')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.operation')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.stage')),
            ],
            options={
                'db_table': 'Chiefdistribution',
            },
        ),
        migrations.CreateModel(
            name='Stagearchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batcharchive')),
            ],
            options={
                'db_table': 'Stagearchive',
            },
        ),
        migrations.CreateModel(
            name='Operationarchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('time_pz', models.DurationField(blank=True, null=True)),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('stage_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.stagearchive')),
            ],
            options={
                'db_table': 'Operationarchive',
            },
        ),
        migrations.CreateModel(
            name='Stagedistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.chiefbatch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.department')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.stage')),
                ('stage_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.stagestatus')),
            ],
            options={
                'db_table': 'Stagedistribution',
            },
        ),
        migrations.CreateModel(
            name='Chiefoperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_distributed', models.BooleanField(default=False)),
                ('chief_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.chiefbatch')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.operation')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.stage')),
                ('distribution_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.stagedistribution')),
            ],
            options={
                'db_table': 'Chiefoperation',
            },
        ),
        migrations.CreateModel(
            name='Operationoperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_plan', models.DurationField(blank=True, null=True)),
                ('time_first_start', models.DateTimeField(blank=True, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_stop', models.DateTimeField(blank=True, null=True)),
                ('time_working', models.DurationField(blank=True, null=True)),
                ('pause', models.BooleanField(blank=True, null=True)),
                ('optimal_part', models.CharField(blank=True, max_length=255, null=True)),
                ('modific', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.area')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batch')),
                ('chief_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.chiefbatch')),
                ('chief_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.chiefoperation')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.machine')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.operation')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.order')),
                ('distribution_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.stagedistribution')),
                ('stage_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.stagestatus')),
            ],
            options={
                'db_table': 'Operationoperator',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название подразделения')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'db_table': 'Subdivision',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.operation')),
            ],
            options={
                'db_table': 'Transfer',
            },
        ),
        migrations.CreateModel(
            name='Transferarchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sh', models.DurationField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('operation_archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.operationarchive')),
            ],
            options={
                'db_table': 'Transferarchive',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('profile_picture', models.FileField(blank=True, null=True, storage=PKMApi.yandex_s3_storage.ClientImgStorage(), upload_to='', verbose_name='Фотография')),
                ('login', models.CharField(max_length=100, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('is_activated', models.BooleanField(blank=True, default=False, null=True, verbose_name='Подтверждённый')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.role', verbose_name='Роль')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.subdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Uploadedreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=0, max_length=100)),
                ('report_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.reporttype')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.user')),
            ],
            options={
                'db_table': 'Uploadedreport',
            },
        ),
        migrations.CreateModel(
            name='Transferoperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_first_start', models.DateTimeField(blank=True, null=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_stop', models.DateTimeField(blank=True, null=True)),
                ('time_working', models.DurationField(blank=True, null=True)),
                ('pause', models.BooleanField(blank=True, null=True)),
                ('opt_path', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batch')),
                ('chief_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.chiefoperation')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.machine')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.operation')),
                ('operator_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.operationoperator')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.order')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.transfer')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.user')),
            ],
            options={
                'db_table': 'Transferoperation',
            },
        ),
        migrations.CreateModel(
            name='Shiftdistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.shift')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.machine')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.user')),
            ],
            options={
                'db_table': 'Shiftdistribution',
            },
        ),
        migrations.AddField(
            model_name='operationoperator',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.user'),
        ),
        migrations.AddField(
            model_name='department',
            name='main_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.user', verbose_name='Начальник цеха'),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.user')),
            ],
            options={
                'db_table': 'Allocation',
            },
        ),
        migrations.CreateModel(
            name='Workershift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('isactive', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.shift')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.user')),
            ],
            options={
                'db_table': 'Workershift',
            },
        ),
        migrations.CreateModel(
            name='Machinework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('indent', models.IntegerField(default=0)),
                ('time_working', models.DurationField(blank=True, null=True)),
                ('isactive', models.BooleanField(blank=True, null=True)),
                ('first_start_batch', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.batch')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.machine')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.shift')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.user')),
                ('work_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.workstatus')),
            ],
            options={
                'db_table': 'Machinework',
            },
        ),
    ]
