# Generated by Django 5.1.2 on 2024-10-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinename',
            name='ratio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Коэффициент многостаночности'),
        ),
        migrations.AlterField(
            model_name='machinename',
            name='tarife',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Сдельный тариф'),
        ),
        migrations.AlterField(
            model_name='machinename',
            name='work_time',
            field=models.CharField(blank=True, null=True, verbose_name='Время работы'),
        ),
    ]
