# Generated by Django 5.1.2 on 2024-12-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_machinename_group_remove_machinename_style'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShiftCalendar',
            new_name='ShiftModeCalendar',
        ),
        migrations.AlterModelTable(
            name='shiftmodecalendar',
            table='ShiftModeCalendar',
        ),
    ]
