# Generated by Django 5.1.2 on 2024-10-31 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_machinename_ratio_alter_machinename_tarife_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinename',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.department', verbose_name='Цех'),
        ),
        migrations.AddField(
            model_name='machinename',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.machinegroup', verbose_name='Группа оборудования'),
        ),
        migrations.AddField(
            model_name='machinename',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.platform', verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='machinename',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.machinestyle', verbose_name='Вид оборудования'),
        ),
        migrations.AlterField(
            model_name='machinename',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.area', verbose_name='Участок'),
        ),
    ]
