# Generated by Django 5.1.2 on 2024-10-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_platform_indent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Код компании'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', to_field='code', verbose_name='Название компании'),
        ),
    ]
