# Generated by Django 5.1.2 on 2024-11-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
