# Generated by Django 5.1.2 on 2024-10-31 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_machinename_department_machinename_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinegroup',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.machinestyle', verbose_name='Вид оборудования'),
        ),
    ]
