# Generated by Django 5.1.2 on 2024-10-17 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_company_code_alter_platform_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Название компании'),
        ),
    ]
