# Generated by Django 5.1.2 on 2024-10-31 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_machinegroup_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftBrigadeCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.brigade', verbose_name='Бригада')),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.shiftday', verbose_name='День недели')),
                ('shift_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.shiftmode', verbose_name='Режим сменности')),
                ('shift_working_day_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.shiftworkingdaymode', verbose_name='Режим рабочего дня')),
            ],
            options={
                'verbose_name': 'Календарь бригады',
                'verbose_name_plural': 'Календари бригад',
                'db_table': 'ShiftBrigadeCalendar',
            },
        ),
    ]
