# Generated by Django 5.1.2 on 2024-11-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_remove_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, null=True, verbose_name='Токен'),
        ),
    ]
