# Generated by Django 5.1.2 on 2024-10-17 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_platform_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.area', verbose_name='Площадка')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.department', verbose_name='Цех')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.platform', verbose_name='Площадка')),
                ('role_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.role', verbose_name='Название роли')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Роль оператора',
                'verbose_name_plural': 'Роли оператора',
                'db_table': 'RoleOperator',
            },
        ),
    ]
