# Generated by Django 5.1.2 on 2024-11-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='session',
        ),
    ]
