# Generated by Django 5.1.2 on 2024-10-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_roleoperator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workershift',
        ),
    ]
