# Generated by Django 5.1.2 on 2024-10-31 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_shiftbrigadecalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.brigade', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'db_table': 'Shift',
            },
        ),
    ]
