# Generated by Django 5.1.2 on 2024-10-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_delete_workershift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shiftdistribution',
        ),
    ]
