# Generated by Django 5.1.2 on 2024-11-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_rename_token_user_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session',
            field=models.BooleanField(blank=True, null=True, verbose_name='Сессия'),
        ),
    ]
