# Generated by Django 5.1.2 on 2024-10-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_delete_shiftdistribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinework',
            name='shift',
        ),
    ]
