# Generated by Django 5.1.2 on 2024-11-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_user_token_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='counter',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Количество устройств'),
        ),
    ]
