# Generated by Django 5.1.2 on 2024-10-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_remove_machinework_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='shift_schedule',
        ),
    ]
