# Generated by Django 5.1.2 on 2024-11-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_remove_allocation_area_allocation_group_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.platform', verbose_name='Площадка'),
        ),
    ]
