# Generated by Django 5.1.2 on 2024-11-20 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_allocation_group_alter_allocation_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.allocation', verbose_name='Распределение')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.department', verbose_name='Цех')),
            ],
            options={
                'db_table': 'AllocationDepartment',
            },
        ),
    ]
