# Generated by Django 5.1.2 on 2024-10-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_remove_machine_shift_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='Shiftschedule',
        ),
    ]
