# Generated by Django 5.1.2 on 2024-11-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_allocationdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.allocation', verbose_name='Распределение')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.area', verbose_name='Участок')),
            ],
            options={
                'db_table': 'AllocationArea',
            },
        ),
    ]
