# Generated by Django 5.1.2 on 2024-10-17 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_delete_shift_delete_shiftschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDayMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Код рабочего дня')),
                ('name', models.CharField(max_length=255, verbose_name='Названние режима рабочего дня')),
                ('start_time', models.TimeField(verbose_name='Время начала смены')),
                ('end_time', models.TimeField(verbose_name='Время конца смены')),
                ('start_pause_1', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 1')),
                ('end_pause_1', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 1')),
                ('start_pause_2', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 2')),
                ('end_pause_2', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 2')),
                ('start_pause_3', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 3')),
                ('end_pause_3', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 3')),
                ('start_pause_4', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 4')),
                ('end_pause_4', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 4')),
                ('start_pause_5', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 5')),
                ('end_pause_5', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 5')),
                ('start_pause_6', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 6')),
                ('end_pause_6', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 6')),
                ('start_pause_7', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 7')),
                ('end_pause_7', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 7')),
                ('start_pause_8', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 8')),
                ('end_pause_8', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 8')),
                ('start_pause_9', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 9')),
                ('end_pause_9', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 9')),
                ('start_pause_10', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 10')),
                ('end_pause_10', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва 10')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Режим рабочего дня',
                'verbose_name_plural': 'Режимы рабочего дня',
                'db_table': 'WorkingDayMode',
            },
        ),
    ]
