# Generated by Django 5.1.2 on 2024-10-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0011_workingdaymode"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.company",
                        verbose_name="Компания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид оборудования",
                "verbose_name_plural": "Виды оборудования",
                "db_table": "MachineStyle",
            },
        ),
        migrations.CreateModel(
            name="MachineGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.machinestyle",
                        verbose_name="Вид оборудования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа оборудования",
                "verbose_name_plural": "Группы оборудования",
                "db_table": "MachineGroup",
            },
        ),
        migrations.CreateModel(
            name="MachineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.machinegroup",
                        verbose_name="Группа оборудования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип оборудования",
                "verbose_name_plural": "Типы оборудования",
                "db_table": "MachineType",
            },
        ),
    ]
