# Generated by Django 5.1.2 on 2024-11-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_allocationarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocationdepartment',
            name='allocation',
        ),
        migrations.RemoveField(
            model_name='allocationdepartment',
            name='department',
        ),
        migrations.AddField(
            model_name='allocation',
            name='area',
            field=models.ManyToManyField(to='Core.area', verbose_name='Участки'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='department',
            field=models.ManyToManyField(to='Core.department', verbose_name='Цеха'),
        ),
        migrations.DeleteModel(
            name='AllocationArea',
        ),
        migrations.DeleteModel(
            name='AllocationDepartment',
        ),
    ]
