# Generated by Django 5.1.2 on 2024-10-19 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0012_machinestyle_machinegroup_machinetype"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inv_number",
                    models.PositiveIntegerField(verbose_name="Инвентарный номер"),
                ),
                (
                    "machine_code",
                    models.CharField(max_length=100, verbose_name="Модель"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "surname",
                    models.CharField(
                        max_length=255, verbose_name="Дополнительное название"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.machinetype",
                        verbose_name="Тип оборудования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель оборудования",
                "verbose_name_plural": "Модели оборудования",
                "db_table": "MachineName",
            },
        ),
    ]
