# Generated by Django 5.1.2 on 2024-11-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_remove_allocationdepartment_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.brigade', verbose_name='Бригада'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.shift', verbose_name='Смена'),
        ),
    ]
