# Generated by Django 5.1.2 on 2024-10-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0013_machinename"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineControlMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Способ управления оборудованием",
                "verbose_name_plural": "Способы управления оборудованием",
                "db_table": "MachineControlMethod",
            },
        ),
        migrations.AddField(
            model_name="machinename",
            name="machine_control_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Core.machinecontrolmethod",
                verbose_name="Способ управления оборудованием",
            ),
        ),
    ]
