# Generated by Django 5.1.2 on 2024-11-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_allocation_brigade_allocation_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_shift',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закончил смену'),
        ),
        migrations.AddField(
            model_name='user',
            name='start_shift',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начал смену'),
        ),
    ]
