# Generated by Django 5.1.2 on 2024-10-21 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0014_machinecontrolmethod_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="detail_machine_type",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="first_machine_type",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="second_machine_type",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="is_activated",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="model",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="name",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="prefix",
        ),
        migrations.AddField(
            model_name="machine",
            name="ratio",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Коэффициент многостачности"
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="tariff",
            field=models.PositiveIntegerField(default=0, verbose_name="Сдельный тариф"),
        ),
        migrations.AlterField(
            model_name="machine",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Core.area",
                verbose_name="Участок",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="invent_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Core.machinename",
                verbose_name="Инвентарный номер",
            ),
        ),
        migrations.DeleteModel(
            name="Detailmachinetype",
        ),
        migrations.DeleteModel(
            name="Firstmachinetype",
        ),
        migrations.DeleteModel(
            name="Secondmachinetype",
        ),
    ]
