# Generated by Django 5.1.2 on 2024-11-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_user_end_shift_user_start_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIG_CALENDAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='ДАТА')),
            ],
            options={
                'verbose_name': 'КАЛЕНДАРЬ',
                'verbose_name_plural': 'КАЛЕНДАРЬ',
                'db_table': 'BIG_CALENDAR',
            },
        ),
    ]
