# Generated by Django 5.1.2 on 2024-10-21 11:27

import PKMApi.yandex_s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0015_remove_machine_detail_machine_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="img",
            field=models.FileField(
                blank=True,
                null=True,
                storage=PKMApi.yandex_s3_storage.ClientImgStorage(),
                upload_to="",
                verbose_name="Фотография",
            ),
        ),
    ]
