# Generated by Django 5.1.2 on 2024-11-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_big_calendar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BIG_CALENDAR',
        ),
    ]
