# Generated by Django 5.1.2 on 2024-10-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0016_machine_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="indent",
            field=models.PositiveIntegerField(default=0, verbose_name="Идентификатор"),
        ),
    ]
