# Generated by Django 5.1.2 on 2024-10-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0017_department_indent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="main_user",
            field=models.CharField(verbose_name="Начальник цеха"),
        ),
    ]
