# Generated by Django 5.1.2 on 2024-10-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0018_alter_department_main_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brigade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, verbose_name="Код бригады")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название бригады"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.area",
                        verbose_name="Участок",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrigadeMachineUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brigade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.brigade",
                        verbose_name="Бригада",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Core.machine",
                        verbose_name="Оборудование",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Core.user",
                        verbose_name="Работник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рспределение бригады",
                "verbose_name_plural": "Распределение бригад",
                "db_table": "BrigadeMachineUser",
            },
        ),
    ]
