# Generated by Django 5.1.2 on 2024-10-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0019_brigade_brigademachineuser"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkingDayMode",
            new_name="ShiftWorkingDayMode",
        ),
        migrations.AlterModelTable(
            name="shiftworkingdaymode",
            table="ShiftWorkingDayMode",
        ),
    ]
