# Generated by Django 5.1.2 on 2024-10-21 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0020_rename_workingdaymode_shiftworkingdaymode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=100, verbose_name="Код режима сменности"
                    ),
                ),
                (
                    "work_hours_per_day",
                    models.PositiveIntegerField(verbose_name="Рабочих часов в день"),
                ),
                (
                    "shifts_per_day",
                    models.PositiveIntegerField(verbose_name="Смен в сутках"),
                ),
                (
                    "hours_in_shifts",
                    models.PositiveIntegerField(verbose_name="Часов в смене"),
                ),
                (
                    "work_days_inline",
                    models.PositiveIntegerField(verbose_name="Рабочих дней в подряд"),
                ),
                (
                    "weekends_inline",
                    models.PositiveIntegerField(verbose_name="Выходных дней в подряд"),
                ),
                (
                    "work_days_per_week",
                    models.PositiveIntegerField(verbose_name="Рабочих дней в неделе"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "shift_working_day_mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Core.shiftworkingdaymode",
                        verbose_name="Режимы рабочего дня",
                    ),
                ),
            ],
        ),
    ]
