# Generated by Django 5.1.2 on 2024-10-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0021_shiftmode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftWeekDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="День недели")),
            ],
        ),
        migrations.CreateModel(
            name="ShiftCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Core.shiftworkingdaymode",
                        verbose_name="Смена",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Core.shiftweekday",
                        verbose_name="День недели",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shiftmode",
            name="shif_calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Core.shiftcalendar",
                verbose_name="Расписание",
            ),
        ),
    ]
