# Generated by Django 5.1.2 on 2024-10-22 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0022_shiftweekday_shiftcalendar_shiftmode_shif_calendar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shiftmode",
            options={
                "verbose_name": "Режим сменности",
                "verbose_name_plural": "Режимы сменности",
            },
        ),
        migrations.AddField(
            model_name="shiftmode",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Core.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="shiftweekday",
            name="name",
            field=models.DateField(max_length=50, verbose_name="День"),
        ),
        migrations.AlterModelTable(
            name="shiftmode",
            table="ShiftMode",
        ),
        migrations.AlterModelTable(
            name="shiftweekday",
            table="ShiftWeekDay",
        ),
    ]
