# Generated by Django 5.1.2 on 2024-10-22 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0023_alter_shiftmode_options_shiftmode_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftmode",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Core.company",
                verbose_name="Компания",
            ),
        ),
    ]
