# Generated by Django 5.1.2 on 2024-10-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0024_alter_shiftmode_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0.0', verbose_name='Версия приложения')),
                ('upd', models.DateField(verbose_name='Обновление от')),
                ('address', models.CharField(verbose_name='Адрес')),
                ('info', models.CharField(default='0', verbose_name='Информация')),
                ('instruction', models.CharField(default='0', verbose_name='Инструкция по эксплуатации')),
            ],
        ),
    ]
