# Generated by Django 5.1.2 on 2024-10-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0025_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinestyle',
            name='name',
            field=models.CharField(default='Резерв', max_length=100, verbose_name='Название'),
        ),
    ]
