# Generated by Django 5.1.2 on 2024-10-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_alter_machinestyle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinestyle',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
