# Generated by Django 5.1.2 on 2024-10-28 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0027_alter_machinestyle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinegroup',
            name='style',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Core.machinestyle', verbose_name='Вид оборудования'),
        ),
    ]
