# Generated by Django 5.1.2 on 2024-10-28 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0028_alter_machinegroup_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinename',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.area', verbose_name='Участок'),
        ),
        migrations.AddField(
            model_name='machinename',
            name='brigade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.brigade', verbose_name='Бригада'),
        ),
        migrations.AddField(
            model_name='machinename',
            name='ratio',
            field=models.PositiveIntegerField(default=0, verbose_name='Коэффициент многостаночности'),
        ),
        migrations.AddField(
            model_name='machinename',
            name='tarife',
            field=models.PositiveIntegerField(default=0, verbose_name='Сдельный тариф'),
        ),
        migrations.AddField(
            model_name='machinename',
            name='work_time',
            field=models.CharField(blank=True, null=True, verbose_name='Время работы'),
        ),
    ]
