# Generated by Django 5.1.2 on 2024-10-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0029_machinename_area_machinename_brigade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinename',
            name='work_time',
            field=models.CharField(null=True, verbose_name='Время работы'),
        ),
    ]
