# Generated by Django 5.1.2 on 2024-10-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0030_alter_machinename_work_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftcalendar',
            name='day',
        ),
        migrations.RemoveField(
            model_name='shiftcalendar',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='shiftmode',
            name='shif_calendar',
        ),
        migrations.AlterModelOptions(
            name='roleoperator',
            options={'verbose_name': 'Роль оператора', 'verbose_name_plural': 'Роль операторов'},
        ),
        migrations.RemoveField(
            model_name='roleoperator',
            name='department',
        ),
        migrations.RemoveField(
            model_name='roleoperator',
            name='platform',
        ),
        migrations.DeleteModel(
            name='ShiftWeekDay',
        ),
        migrations.DeleteModel(
            name='ShiftCalendar',
        ),
    ]
