# Generated by Django 5.1.2 on 2024-10-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0031_remove_shiftcalendar_day_remove_shiftcalendar_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название дня недели')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
                'db_table': 'ShiftDay',
            },
        ),
    ]
