# Generated by Django 5.1.2 on 2024-10-28 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0032_shiftday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='День недели')),
                ('shift_working_day_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.shiftworkingdaymode', verbose_name='Режим рабочего дня')),
            ],
            options={
                'verbose_name': 'Календарь',
                'verbose_name_plural': 'Календари',
                'db_table': 'ShiftCalendar',
            },
        ),
    ]
