# Generated by Django 5.1.2 on 2024-10-28 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0033_shiftcalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftcalendar',
            name='shift_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.shiftmode', verbose_name='Режим сменности'),
        ),
        migrations.AlterField(
            model_name='shiftworkingdaymode',
            name='end_pause_1',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 1'),
        ),
        migrations.AlterField(
            model_name='shiftworkingdaymode',
            name='end_pause_10',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 10'),
        ),
        migrations.AlterField(
            model_name='shiftworkingdaymode',
            name='end_pause_2',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 2'),
        ),
        migrations.AlterField(
            model_name='shiftworkingdaymode',
            name='end_pause_3',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 3'),
        ),
        migrations.AlterField(
            model_name='shiftworkingdaymode',
            name='end_pause_4',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 4'),
        ),
        migrations.AlterField(
            model_name='shiftworkingdaymode',
            name='end_pause_5',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 5'),
        ),
        migrations.AlterField(
            model_name='shiftworkingdaymode',
            name='end_pause_6',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 6'),
        ),
        migrations.AlterField(
            model_name='shiftworkingdaymode',
            name='end_pause_7',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 7'),
        ),
        migrations.AlterField(
            model_name='shiftworkingdaymode',
            name='end_pause_8',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 8'),
        ),
        migrations.AlterField(
            model_name='shiftworkingdaymode',
            name='end_pause_9',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец перерыва 9'),
        ),
    ]
