# Generated by Django 5.1.2 on 2024-10-28 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0034_shiftcalendar_shift_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftcalendar',
            name='shift_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.shiftmode', verbose_name='Режим сменности'),
        ),
    ]
