# Generated by Django 5.1.2 on 2024-10-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0035_alter_shiftcalendar_shift_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftmode',
            name='shift_working_day_mode',
            field=models.CharField(verbose_name='Режимы рабочего дня'),
        ),
    ]
