# Generated by Django 5.1.2 on 2024-10-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0036_alter_shiftmode_shift_working_day_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftcalendar',
            name='day',
        ),
    ]
