# Generated by Django 5.1.2 on 2024-10-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0037_remove_shiftcalendar_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftcalendar',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.shiftday', verbose_name='День недели'),
        ),
    ]
