# Generated by Django 5.1.2 on 2024-10-30 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0038_shiftcalendar_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftcalendar',
            name='shift_working_day_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.shiftworkingdaymode', verbose_name='Режим рабочего дня'),
        ),
    ]
