# Generated by Django 5.1.2 on 2024-10-30 09:00

import PKMApi.yandex_s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0039_alter_shiftcalendar_shift_working_day_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='area',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='invent_number',
        ),
        migrations.RemoveField(
            model_name='transferoperation',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='operationoperator',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='machinework',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='machinework',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='machinework',
            name='user',
        ),
        migrations.RemoveField(
            model_name='machinework',
            name='work_status',
        ),
        migrations.RemoveField(
            model_name='operationoperator',
            name='area',
        ),
        migrations.RemoveField(
            model_name='operationoperator',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='operationoperator',
            name='chief_batch',
        ),
        migrations.RemoveField(
            model_name='operationoperator',
            name='chief_operation',
        ),
        migrations.RemoveField(
            model_name='operationoperator',
            name='distribution_stage',
        ),
        migrations.RemoveField(
            model_name='operationoperator',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='operationoperator',
            name='order',
        ),
        migrations.RemoveField(
            model_name='operationoperator',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='operationoperator',
            name='stage_status',
        ),
        migrations.RemoveField(
            model_name='transferoperation',
            name='operator_operation',
        ),
        migrations.RemoveField(
            model_name='transferoperation',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='transferoperation',
            name='chief_operation',
        ),
        migrations.RemoveField(
            model_name='transferoperation',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='transferoperation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transferoperation',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='transferoperation',
            name='transfer',
        ),
        migrations.AddField(
            model_name='machinename',
            name='img',
            field=models.FileField(blank=True, null=True, storage=PKMApi.yandex_s3_storage.ClientImgStorage(), upload_to='', verbose_name='Фотография'),
        ),
        migrations.DeleteModel(
            name='BrigadeMachineUser',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Machinework',
        ),
        migrations.DeleteModel(
            name='Operationoperator',
        ),
        migrations.DeleteModel(
            name='Transferoperation',
        ),
    ]
