# Generated by Django 5.1.2 on 2024-10-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0040_remove_machine_area_remove_machine_invent_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinename',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Core.area', verbose_name='Участок'),
        ),
    ]
