# Generated by Django 5.1.2 on 2024-10-30 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0041_alter_machinename_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinename',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.machinetype', verbose_name='Тип оборудования'),
        ),
    ]
