# Generated by Django 5.1.2 on 2024-10-30 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0042_alter_machinename_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinename',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='machinename',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Core.brigade', verbose_name='Бригада'),
        ),
    ]
