# Generated by Django 5.1.2 on 2024-10-30 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0043_machinename_company_alter_machinename_brigade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinename',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Компания'),
        ),
    ]
