# Generated by Django 5.1.2 on 2024-10-30 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0044_alter_machinename_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinename',
            options={'verbose_name': 'Карточка оборудования', 'verbose_name_plural': 'Карточки оборудования'},
        ),
        migrations.AddField(
            model_name='machinecontrolmethod',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Компания'),
        ),
    ]
