# Generated by Django 5.1.2 on 2024-10-30 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0045_alter_machinename_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinecontrolmethod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='Компания'),
        ),
    ]
