# Generated by Django 5.1.2 on 2024-10-30 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0046_alter_machinecontrolmethod_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinename',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.brigade', verbose_name='Бригада'),
        ),
    ]
