# Generated by Django 5.1.2 on 2024-11-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BIG_CALENDAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.DateField(verbose_name='ДАТА')),
            ],
            options={
                'verbose_name': 'КАЛЕНДАРЬ',
                'verbose_name_plural': 'КАЛЕНДАРЬ',
                'db_table': 'BIG_CALENDAR',
            },
        ),
    ]
