# Generated by Django 5.1.2 on 2024-11-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BIG_CALENDAR_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='big_calendar',
            old_name='week_day',
            new_name='day',
        ),
    ]
